### ISSUE TITLE
Can HOME icon take you to $HOME instead of /?

### ISSUE THREAD

**Issue by aramirezreyes** [NERSC/jupyterhub-deploy#61]
The home icon in the file explorer currently takes you to the root directory, and as some folders have restricted permissions, if you don't have an open file it is impossible to navigate the finder up to you user folder. Only solution: exit the service and log in again.

Is it possible to make the 'home' icon in the file browser to take you to $HOME instead of the root?

**Comment by rcthomas** [comment]
This has more to do with how JupyterLab works than with our deployment.  I suggest filing an issue [there.](https://github.com/jupyterlab/jupyterlab/issues)  However from our conversations with the developers it sounds like they intend the home icon to represent something other than the concept of a user's home directory, or else assume that the system is configured so that's the only place you look.  We don't assume that in our deployment.  Another way to "resolve" it would be to change the home picture to a slash.
